# Generated by Django 4.0.4 on 2022-05-01 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Apertura', models.TimeField(default=datetime.time(8, 0))),
                ('Cierre', models.TimeField(default=datetime.time(19, 0))),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('calidad_internet', models.DecimalField(decimal_places=1, max_digits=2)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=2)),
                ('correo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
