# Generated by Django 4.0.4 on 2022-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(max_length=5)),
                ('calidad_internet', models.DecimalField(decimal_places=1, max_digits=2)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
