# Generated by Django 4.0.4 on 2022-05-01 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_establecimiento_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='horario',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='Apertura',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='Cierre',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
