# Generated by Django 4.0.4 on 2022-05-01 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_establecimiento_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='Cierre',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
